# Generated by Django 4.2 on 2023-04-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botForward_api', '0002_remove_post_image_alter_post_text_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FilePathField(path='/home/komediantto/Dev/BotForwarding/api/app/media'),
        ),
    ]
