# Generated by Django 4.2 on 2023-04-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botForward_api', '0003_alter_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='media_type',
        ),
    ]
