# Generated by Django 4.2 on 2023-04-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botForward_api', '0004_remove_media_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.URLField(default='none'),
            preserve_default=False,
        ),
    ]
