# Generated by Django 4.2 on 2023-04-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botForward_api', '0005_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_path',
            field=models.FilePathField(default='asd', path='/home/komediantto/Dev/BotForwarding/api/app/media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
