# Generated by Django 4.2 on 2023-04-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botForward_api', '0007_remove_media_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='url',
        ),
    ]
