# Generated by Django 4.2 on 2023-04-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botForward_api', '0008_remove_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
