# Generated by Django 4.2 on 2023-05-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botForward_api', '0012_alter_settings_options_remove_settings_channels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='ID канала')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя канала')),
                ('activ', models.BooleanField(default=False, verbose_name='Активирован')),
                ('parse_channels', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_channels', to='botForward_api.channel')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='channels1', to='botForward_api.settings')),
            ],
        ),
    ]
