# Generated by Django 4.2 on 2023-05-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botForward_api', '0013_targetchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetchannel',
            name='name',
            field=models.CharField(blank=True, default=1, max_length=300, verbose_name='Имя канала'),
            preserve_default=False,
        ),
    ]
