# Generated by Django 4.2 on 2023-05-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botForward_api', '0015_alter_targetchannel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetchannel',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_channels', to='botForward_api.settings'),
        ),
    ]
