# Generated by Django 4.2 on 2023-05-10 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botForward_api', '0016_alter_targetchannel_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetchannel',
            name='parse_channels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_channels', to='botForward_api.channel'),
        ),
    ]
