# Generated by Django 4.2 on 2023-05-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botForward_api', '0017_alter_targetchannel_parse_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='targetchannel',
            name='parse_channels',
        ),
        migrations.AddField(
            model_name='channel',
            name='target_channels',
            field=models.ManyToManyField(related_name='channels', to='botForward_api.targetchannel'),
        ),
    ]
