# Generated by Django 4.2 on 2023-06-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botForward_api', '0019_remove_targetchannel_settings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_string', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='target_channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='botForward_api.targetchannel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='targetchannel',
            name='activ',
            field=models.BooleanField(default=False, verbose_name='Включить парсинг'),
        ),
        migrations.AlterField(
            model_name='targetchannel',
            name='forwarding',
            field=models.BooleanField(default=False, verbose_name='Парсинг прямо в канал'),
        ),
    ]
